Github auth
frolovdev/bestyjs pull request #1
Opened 2021-12-14 13:53 UTC by ippsav

first commit:
- Getting github code from frontend.
- Sending it to the worker.
- Fetching the access token from github api using the worker.
- Setting the access token as a cookie for frontend.

2021-12-16 09:14 UTC, frolovdev commented on .gitignore
> +.env
let's add

.editorconfig file

```
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

2021-12-16 09:14 UTC, frolovdev commented on backend/package.json
> +    "dev": "miniflare --live-reload --debug --env .env.local",
🔥

2021-12-16 09:16 UTC, frolovdev commented on frontend/src/App.tsx
> +          }
let's move to function in component

handleAuth

2021-12-16 09:22 UTC, frolovdev commented on backend/package.json
> +    "cookie": "^0.4.1"
do we really need this pacakge?

https://github.com/jshttp/cookie/blob/master/index.js#L49-L83

We only need the parse function, that we can implement by ourselves

2021-12-16 09:23 UTC, frolovdev commented on backend/src/index.ts
> +  const {code} = await request.json();
as far as I can see we don't have prettier in backend part, I will add it after your pull requests

2021-12-16 09:25 UTC, frolovdev commented on backend/src/index.ts
> +      'Set-Cookie': `qid=${access_token};SameSite=Lax; HttpOnly`
does it work as expected? Did you get a cookie in an application tab in chrome?

2021-12-16 09:26 UTC, frolovdev commented on frontend/src/App.tsx
> +const SCOPES = 'read:org,read:user'
could you provide an explanation for scopes?

(don't use caps for consts 🙏 )

2021-12-16 09:27 UTC, frolovdev commented on frontend/src/App.tsx
> +  }, [])
```
  const fetchAccessToken = async (githubAccessCode: string) => {
    return await fetch('http://localhost:3000/worker1', {
      headers: {
        'Content-Type': 'application/json',
      },
      method: 'POST',
      body: JSON.stringify({ code: githubAccessCode }),
    })
  }
  useEffect(() => {
    const fetch = async () => {}

   fetch()
  }, [])
```

2021-12-16 09:27 UTC, frolovdev requested changes
mostly great work but let's do some iterations over it, because you can do much better 🚀

2021-12-16 09:39 UTC, frolovdev commented
Also, a word for future work, the smaller changes you will deliver the better for transparency of this project, take this into view 🙏

2021-12-18 15:56 UTC, ippsav commented on backend/package.json
> +    "cookie": "^0.4.1"
Done :+1:

2021-12-18 16:00 UTC, ippsav commented on frontend/src/App.tsx
> +const SCOPES = 'read:org,read:user'
-read:org: to have access to read-only to private/org repos
- read:user: Used only for auth to check if the cookie is valid by doing a request to github api, if the response is 200 then the cookie is valid ( to avoid getting a new accessToken each time the user login if he already has a valid no expired one)

2021-12-18 16:02 UTC, ippsav commented on backend/src/common/cookie/parser.ts
> +}
custom parser for cookie

2021-12-18 16:02 UTC, ippsav commented on backend/src/index.ts
> +      'Set-Cookie': `qid=${access_token};SameSite=Lax; HttpOnly`
Yes it does
![image](https://user-images.githubusercontent.com/69125922/146647585-36a33121-f4f0-4946-a985-adf52d0c734b.png)

2021-12-19 12:08 UTC, frolovdev commented
I close this pr because it's a stale one

2021-12-19 12:08 UTC, closed without merging